CREATE TABLE IF NOT EXISTS app_state (
  id INT PRIMARY KEY,
  json LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO app_state (id, json)
VALUES (1, '{}')
ON DUPLICATE KEY UPDATE json = VALUES(json);

CREATE TABLE IF NOT EXISTS patients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  external_id VARCHAR(64) NOT NULL UNIQUE,
  nome VARCHAR(255) DEFAULT NULL,
  cpf VARCHAR(50) DEFAULT NULL,
  tel VARCHAR(50) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  tipo_atendimento VARCHAR(100) DEFAULT NULL,
  data_cadastro DATETIME DEFAULT NULL,
  payload_json LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS appointments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  external_id VARCHAR(64) NOT NULL UNIQUE,
  paciente_id VARCHAR(64) DEFAULT NULL,
  paciente_nome VARCHAR(255) DEFAULT NULL,
  data_consulta DATE DEFAULT NULL,
  hora_consulta TIME DEFAULT NULL,
  status VARCHAR(50) DEFAULT NULL,
  valor DECIMAL(12,2) DEFAULT NULL,
  payload_json LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS financial_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  external_id VARCHAR(64) NOT NULL UNIQUE,
  entry_type VARCHAR(20) DEFAULT NULL,
  categoria VARCHAR(100) DEFAULT NULL,
  descricao VARCHAR(255) DEFAULT NULL,
  status VARCHAR(50) DEFAULT NULL,
  data_lancamento DATE DEFAULT NULL,
  valor DECIMAL(12,2) DEFAULT NULL,
  origem VARCHAR(100) DEFAULT NULL,
  payload_json LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  external_id VARCHAR(64) NOT NULL UNIQUE,
  nome VARCHAR(255) DEFAULT NULL,
  lote VARCHAR(100) DEFAULT NULL,
  validade DATE DEFAULT NULL,
  qtd INT DEFAULT NULL,
  custo DECIMAL(12,2) DEFAULT NULL,
  preco DECIMAL(12,2) DEFAULT NULL,
  payload_json LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS protocols (
  id INT AUTO_INCREMENT PRIMARY KEY,
  external_id VARCHAR(64) NOT NULL UNIQUE,
  nome VARCHAR(255) DEFAULT NULL,
  valor DECIMAL(12,2) DEFAULT NULL,
  duracao INT DEFAULT NULL,
  payload_json LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
